### GET ONE

GET http://localhost:80/articles/1
### GET ONE With details

GET http://localhost:80/articles/1?expand=ArticleType

### GET MANY

GET http://localhost:80/articles

### GET MANY WITH FILTER
GET http://localhost:80/articles?condition=name%20eq%20Tennis

### GET MANY WITH ORDERING

GET http://localhost:80/articles?order=name


### GET MANY with details

GET http://localhost:80/articles?expand=ArticleType

### DELETE

DELETE http://localhost:80/articles/3

### CREATE

POST http://localhost:80/articles

  {
    "Name": "Smoking Pant",
    "Price": 65,
    "ArticleTypeID": 2
  }