### GET ONE

GET http://localhost:8080/invoices/1
### GET ONE With details

GET http://localhost:8080/invoices/1?expand=Client,InvoiceLine,InvoiceLine.Article

### GET MANY

GET http://localhost:8080/invoices

### GET MANY with details

GET http://localhost:8080/invoices?expand=Client




### CREATE

POST http://localhost:8080/invoices

  {
    "Name": "Smoking Pant",
    "Price": 65,
    "ArticleTypeID": 2
  }

